
{1: 'Alpine (GBV)',
 2: 'Inyo (GBV)',
 3: 'Mono (GBV)',
 4: 'Lake (LC)',
 5: 'El Dorado (LT)',
 6: 'Placer (LT)',
 7: 'Amador (MC)',
 8: 'Calaveras (MC)',
 9: 'El Dorado (MC)',
 10: 'Mariposa (MC)',
 11: 'Nevada (MC)',
 12: 'Placer (MC)',
 13: 'Plumas (MC)',
 14: 'Sierra (MC)',
 15: 'Tuolumne (MC)',
 16: 'Monterey (NCC)',
 17: 'San Benito (NCC)',
 18: 'Santa Cruz (NCC)',
 19: 'Del Norte (NC)',
 20: 'Humboldt (NC)',
 21: 'Mendocino (NC)',
 22: 'Sonoma (NC)',
 23: 'Trinity (NC)',
 24: 'Lassen (NEP)',
 25: 'Modoc (NEP)',
 26: 'Siskiyou (NEP)',
 27: 'Butte (SV)',
 28: 'Colusa (SV)',
 29: 'Glenn (SV)',
 30: 'Placer (SV)',
 31: 'Sacramento (SV)',
 32: 'Shasta (SV)',
 33: 'Solano (SV)',
 34: 'Sutter (SV)',
 35: 'Tehama (SV)',
 36: 'Yolo (SV)',
 37: 'Yuba (SV)',
 38: 'San Diego (SD)',
 39: 'Alameda (SF)',
 40: 'Contra Costa (SF)',
 41: 'Marin (SF)',
 42: 'Napa (SF)',
 43: 'San Francisco (SF)',
 44: 'San Mateo (SF)',
 45: 'Santa Clara (SF)',
 46: 'Solano (SF)',
 47: 'Sonoma (SF)',
 48: 'Fresno (SJV)',
 49: 'Kern (SJV)',
 50: 'Kings (SJV)',
 51: 'Madera (SJV)',
 52: 'Merced (SJV)',
 53: 'San Joaquin (SJV)',
 54: 'Stanislaus (SJV)',
 55: 'Tulare (SJV)',
 56: 'San Luis Obispo (SCC)',
 57: 'Santa Barbara (SCC)',
 58: 'Ventura (SCC)',
 59: 'Los Angeles (SC)',
 60: 'Orange (SC)',
 61: 'Riverside (SC)',
 62: 'San Bernardino (SC)',
 63: 'Imperial (SS)',
 64: 'Riverside (SS)',
 65: 'Kern (MD)',
 66: 'Riverside (MDMDAQMD)',
 67: 'Riverside (MDSCAQMD)',
 68: 'Los Angeles (MD)',
 69: 'San Bernardino (MD)'}
