
{1:   {'air_basin': 'GBV', 'county': 2,  'district': 'GBU', 'name': 'Alpine (GBV)'},
 2:   {'air_basin': 'GBV', 'county': 14, 'district': 'GBU', 'name': 'Inyo (GBV)'},
 3:   {'air_basin': 'GBV', 'county': 26, 'district': 'GBU', 'name': 'Mono (GBV)'},
 4:   {'air_basin': 'LC',  'county': 17, 'district': 'LAK', 'name': 'Lake (LC)'},
 5:   {'air_basin': 'LT',  'county': 9,  'district': 'ED',  'name': 'El Dorado (LT)'},
 6:   {'air_basin': 'LT',  'county': 31, 'district': 'PLA', 'name': 'Placer (LT)'},
 7:   {'air_basin': 'MC',  'county': 3,  'district': 'AMA', 'name': 'Amador (MC)'},
 8:   {'air_basin': 'MC',  'county': 5,  'district': 'CAL', 'name': 'Calaveras (MC)'},
 9:   {'air_basin': 'MC',  'county': 9,  'district': 'ED',  'name': 'El Dorado (MC)'},
 10:  {'air_basin': 'MC',  'county': 22, 'district': 'MPA', 'name': 'Mariposa (MC)'},
 11:  {'air_basin': 'MC',  'county': 29, 'district': 'NSI', 'name': 'Nevada (MC)'},
 12:  {'air_basin': 'MC',  'county': 31, 'district': 'PLA', 'name': 'Placer (MC)'},
 13:  {'air_basin': 'MC',  'county': 32, 'district': 'NSI', 'name': 'Plumas (MC)'},
 14:  {'air_basin': 'MC',  'county': 46, 'district': 'NSI', 'name': 'Sierra (MC)'},
 15:  {'air_basin': 'MC',  'county': 55, 'district': 'TUO', 'name': 'Tuolumne (MC)'},
 16:  {'air_basin': 'NCC', 'county': 27, 'district': 'MBU', 'name': 'Monterey (NCC)'},
 17:  {'air_basin': 'NCC', 'county': 35, 'district': 'MBU', 'name': 'San Benito (NCC)'},
 18:  {'air_basin': 'NCC', 'county': 44, 'district': 'MBU', 'name': 'Santa Cruz (NCC)'},
 19:  {'air_basin': 'NC',  'county': 8,  'district': 'NCU', 'name': 'Del Norte (NC)'},
 20:  {'air_basin': 'NC',  'county': 12, 'district': 'NCU', 'name': 'Humboldt (NC)'},
 21:  {'air_basin': 'NC',  'county': 23, 'district': 'MEN', 'name': 'Mendocino (NC)'},
 22:  {'air_basin': 'NC',  'county': 49, 'district': 'NS',  'name': 'Sonoma (NC)'},
 23:  {'air_basin': 'NC',  'county': 53, 'district': 'NCU', 'name': 'Trinity (NC)'},
 24:  {'air_basin': 'NEP', 'county': 18, 'district': 'LAS', 'name': 'Lassen (NEP)'},
 25:  {'air_basin': 'NEP', 'county': 25, 'district': 'MOD', 'name': 'Modoc (NEP)'},
 26:  {'air_basin': 'NEP', 'county': 47, 'district': 'SIS', 'name': 'Siskiyou (NEP)'},
 27:  {'air_basin': 'SV',  'county': 4,  'district': 'BUT', 'name': 'Butte (SV)'},
 28:  {'air_basin': 'SV',  'county': 6,  'district': 'COL', 'name': 'Colusa (SV)'},
 29:  {'air_basin': 'SV',  'county': 11, 'district': 'GLE', 'name': 'Glenn (SV)'},
 30:  {'air_basin': 'SV',  'county': 31, 'district': 'PLA', 'name': 'Placer (SV)'},
 31:  {'air_basin': 'SV',  'county': 34, 'district': 'SAC', 'name': 'Sacramento (SV)'},
 32:  {'air_basin': 'SV',  'county': 45, 'district': 'SHA', 'name': 'Shasta (SV)'},
 33:  {'air_basin': 'SV',  'county': 48, 'district': 'YS',  'name': 'Solano (SV)'},
 34:  {'air_basin': 'SV',  'county': 51, 'district': 'FR',  'name': 'Sutter (SV)'},
 35:  {'air_basin': 'SV',  'county': 52, 'district': 'TEH', 'name': 'Tehama (SV)'},
 36:  {'air_basin': 'SV',  'county': 57, 'district': 'YS',  'name': 'Yolo (SV)'},
 37:  {'air_basin': 'SV',  'county': 58, 'district': 'FR',  'name': 'Yuba (SV)'},
 38:  {'air_basin': 'SD',  'county': 37, 'district': 'SD',  'name': 'San Diego (SD)'},
 39:  {'air_basin': 'SF',  'county': 1,  'district': 'BA',  'name': 'Alameda (SF)'},
 40:  {'air_basin': 'SF',  'county': 7,  'district': 'BA',  'name': 'Contra Costa (SF)'},
 41:  {'air_basin': 'SF',  'county': 21, 'district': 'BA',  'name': 'Marin (SF)'},
 42:  {'air_basin': 'SF',  'county': 28, 'district': 'BA',  'name': 'Napa (SF)'},
 43:  {'air_basin': 'SF',  'county': 38, 'district': 'BA',  'name': 'San Francisco (SF)'},
 44:  {'air_basin': 'SF',  'county': 41, 'district': 'BA',  'name': 'San Mateo (SF)'},
 45:  {'air_basin': 'SF',  'county': 43, 'district': 'BA',  'name': 'Santa Clara (SF)'},
 46:  {'air_basin': 'SF',  'county': 48, 'district': 'BA',  'name': 'Solano (SF)'},
 47:  {'air_basin': 'SF',  'county': 49, 'district': 'BA',  'name': 'Sonoma (SF)'},
 48:  {'air_basin': 'SJV', 'county': 10, 'district': 'SJU', 'name': 'Fresno (SJV)'},
 49:  {'air_basin': 'SJV', 'county': 15, 'district': 'SJU', 'name': 'Kern (SJV)'},
 50:  {'air_basin': 'SJV', 'county': 16, 'district': 'SJU', 'name': 'Kings (SJV)'},
 51:  {'air_basin': 'SJV', 'county': 20, 'district': 'SJU', 'name': 'Madera (SJV)'},
 52:  {'air_basin': 'SJV', 'county': 24, 'district': 'SJU', 'name': 'Merced (SJV)'},
 53:  {'air_basin': 'SJV', 'county': 39, 'district': 'SJU', 'name': 'San Joaquin (SJV)'},
 54:  {'air_basin': 'SJV', 'county': 50, 'district': 'SJU', 'name': 'Stanislaus (SJV)'},
 55:  {'air_basin': 'SJV', 'county': 54, 'district': 'SJU', 'name': 'Tulare (SJV)'},
 56:  {'air_basin': 'SCC', 'county': 40, 'district': 'SLO', 'name': 'San Luis Obispo (SCC)'},
 57:  {'air_basin': 'SCC', 'county': 42, 'district': 'SB',  'name': 'Santa Barbara (SCC)'},
 58:  {'air_basin': 'SCC', 'county': 56, 'district': 'VEN', 'name': 'Ventura (SCC)'},
 59:  {'air_basin': 'SC',  'county': 19, 'district': 'SC',  'name': 'Los Angeles (SC)'},
 60:  {'air_basin': 'SC',  'county': 30, 'district': 'SC',  'name': 'Orange (SC)'},
 61:  {'air_basin': 'SC',  'county': 33, 'district': 'SC',  'name': 'Riverside (SC)'},
 62:  {'air_basin': 'SC',  'county': 36, 'district': 'SC',  'name': 'San Bernardino (SC)'},
 63:  {'air_basin': 'SS',  'county': 13, 'district': 'IMP', 'name': 'Imperial (SS)'},
 64:  {'air_basin': 'SS',  'county': 33, 'district': 'SC',  'name': 'Riverside (SS)'},
 65:  {'air_basin': 'MD',  'county': 15, 'district': 'KER', 'name': 'Kern (MD)'},
 66:  {'air_basin': 'MD',  'county': 33, 'district': 'MOJ', 'name': 'Riverside (MDMDAQMD)'},
 67:  {'air_basin': 'MD',  'county': 33, 'district': 'SC',  'name': 'Riverside (MDSCAQMD)'},
 68:  {'air_basin': 'MD',  'county': 19, 'district': 'AV',  'name': 'Los Angeles (MD)'},
 69:  {'air_basin': 'MD',  'county': 36, 'district': 'MOJ', 'name': 'San Bernardino (MD)'},
 70:  {'air_basin': 'OCS', 'county': 8,  'district': 'NCU', 'name': 'OCS (NCU)'},
 71:  {'air_basin': 'OCS', 'county': 12, 'district': 'NCU', 'name': 'OCS (NCU)'},
 72:  {'air_basin': 'OCS', 'county': 19, 'district': 'SC',  'name': 'OCS (SC)'},
 73:  {'air_basin': 'OCS', 'county': 21, 'district': 'BA',  'name': 'OCS (BA)'},
 74:  {'air_basin': 'OCS', 'county': 23, 'district': 'MEN', 'name': 'OCS (MEN)'},
 75:  {'air_basin': 'OCS', 'county': 27, 'district': 'MBU', 'name': 'OCS (MBU)'},
 76:  {'air_basin': 'OCS', 'county': 30, 'district': 'SC',  'name': 'OCS (SC)'},
 77:  {'air_basin': 'OCS', 'county': 37, 'district': 'SD',  'name': 'OCS (SD)'},
 78:  {'air_basin': 'OCS', 'county': 38, 'district': 'BA',  'name': 'OCS (BA)'},
 79:  {'air_basin': 'OCS', 'county': 40, 'district': 'SLO', 'name': 'OCS (SLO)'},
 80:  {'air_basin': 'OCS', 'county': 41, 'district': 'BA',  'name': 'OCS (BA)'},
 81:  {'air_basin': 'OCS', 'county': 42, 'district': 'SB',  'name': 'OCS (SB)'},
 82:  {'air_basin': 'OCS', 'county': 44, 'district': 'MBU', 'name': 'OCS (MBU)'},
 83:  {'air_basin': 'OCS', 'county': 49, 'district': 'BA',  'name': 'OCS (BA)'},
 84:  {'air_basin': 'OCS', 'county': 49, 'district': 'NS',  'name': 'OCS (NS)'},
 85:  {'air_basin': 'OCS', 'county': 56, 'district': 'VEN', 'name': 'OCS (VEN)'},
 86:  {'air_basin': 'OC1', 'county': 8,  'district': 'NCU', 'name': 'OC1 (NCU)'},
 87:  {'air_basin': 'OC1', 'county': 12, 'district': 'NCU', 'name': 'OC1 (NCU)'},
 88:  {'air_basin': 'OC1', 'county': 19, 'district': 'SC',  'name': 'OC1 (SC)'},
 89:  {'air_basin': 'OC1', 'county': 21, 'district': 'BA',  'name': 'OC1 (BA)'},
 90:  {'air_basin': 'OC1', 'county': 23, 'district': 'MEN', 'name': 'OC1 (MEN)'},
 91:  {'air_basin': 'OC1', 'county': 27, 'district': 'MBU', 'name': 'OC1 (MBU)'},
 92:  {'air_basin': 'OC1', 'county': 30, 'district': 'SC',  'name': 'OC1 (SC)'},
 93:  {'air_basin': 'OC1', 'county': 37, 'district': 'SD',  'name': 'OC1 (SD)'},
 94:  {'air_basin': 'OC1', 'county': 38, 'district': 'BA',  'name': 'OC1 (BA)'},
 95:  {'air_basin': 'OC1', 'county': 40, 'district': 'SLO', 'name': 'OC1 (SLO)'},
 96:  {'air_basin': 'OC1', 'county': 41, 'district': 'BA',  'name': 'OC1 (BA)'},
 97:  {'air_basin': 'OC1', 'county': 42, 'district': 'SB',  'name': 'OC1 (SB)'},
 98:  {'air_basin': 'OC1', 'county': 44, 'district': 'MBU', 'name': 'OC1 (MBU)'},
 99:  {'air_basin': 'OC1', 'county': 49, 'district': 'BA',  'name': 'OC1 (BA)'},
 100: {'air_basin': 'OC1', 'county': 49, 'district': 'NS',  'name': 'OC1 (NS)'},
 101: {'air_basin': 'OC1', 'county': 56, 'district': 'VEN', 'name': 'OC1 (VEN)'},
 102: {'air_basin': 'OC2', 'county': 8,  'district': 'NCU', 'name': 'OC2 (NCU)'},
 103: {'air_basin': 'OC2', 'county': 12, 'district': 'NCU', 'name': 'OC2 (NCU)'},
 104: {'air_basin': 'OC2', 'county': 19, 'district': 'SC',  'name': 'OC2 (SC)'},
 105: {'air_basin': 'OC2', 'county': 21, 'district': 'BA',  'name': 'OC2 (BA)'},
 106: {'air_basin': 'OC2', 'county': 23, 'district': 'MEN', 'name': 'OC2 (MEN)'},
 107: {'air_basin': 'OC2', 'county': 27, 'district': 'MBU', 'name': 'OC2 (MBU)'},
 108: {'air_basin': 'OC2', 'county': 30, 'district': 'SC',  'name': 'OC2 (SC)'},
 109: {'air_basin': 'OC2', 'county': 37, 'district': 'SD',  'name': 'OC2 (SD)'},
 110: {'air_basin': 'OC2', 'county': 38, 'district': 'BA',  'name': 'OC2 (BA)'},
 111: {'air_basin': 'OC2', 'county': 40, 'district': 'SLO', 'name': 'OC2 (SLO)'},
 112: {'air_basin': 'OC2', 'county': 41, 'district': 'BA',  'name': 'OC2 (BA)'},
 113: {'air_basin': 'OC2', 'county': 42, 'district': 'SB',  'name': 'OC2 (SB)'},
 114: {'air_basin': 'OC2', 'county': 44, 'district': 'MBU', 'name': 'OC2 (MBU)'},
 115: {'air_basin': 'OC2', 'county': 49, 'district': 'BA',  'name': 'OC2 (BA)'},
 116: {'air_basin': 'OC2', 'county': 49, 'district': 'NS',  'name': 'OC2 (NS)'},
 117: {'air_basin': 'OC2', 'county': 56, 'district': 'VEN', 'name': 'OC2 (VEN)'}}
